version: '3'

services:
  backend1:
    build: ./backend1
    container_name: backend1
    networks:
      - app-network
    restart: always

  backend2:
    build: ./backend2
    container_name: backend2
    networks:
      - app-network
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"  # Expose HTTP port to host
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config
    restart: always

networks:
  app-network:
    driver: bridge
